# Generated by Django 4.2.3 on 2023-08-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='manufacturehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.IntegerField(blank=True, null=True)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(max_length=6)),
                ('is_complete', models.BooleanField()),
            ],
        ),
    ]
