# Generated by Django 4.2.2 on 2023-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.IntegerField(blank=True, null=True)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
