# Generated by Django 4.2.3 on 2023-08-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manufacture', to='Items.items'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacture',
            name='manufacturehistory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_manufacture', to='Manufacture.manufacturehistory'),
            preserve_default=False,
        ),
    ]
