# Generated by Django 4.2.2 on 2023-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacture', '0002_manufacturehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturehistory',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
