name: Deploy using AWS SSM Send-Command 

on:
push:
branches: [master]

jobs:
start:
runs-on: ubuntu-latest 

steps:
			  - uses: actions/checkout@v2

			  - name: AWS SSM Send Command
			  uses: peterkimzz/aws-ssm-send-command@1.0.1
			  with:
			  aws-assume-role: ${{ secrets.AWS_ASSUME_ROLE }}
			  aws-region: us-west-2
			  instance-ids: ${{ secrets.INSTANCE_ID  }}
			  comment: Deploy the master branch
			  working-directory: /home/ec2-user/prototype
			  command: /bin/sh ./deploy.sh