# Generated by Django 4.2.1 on 2023-05-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
