# Generated by Django 4.2.1 on 2023-05-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.AddField(
            model_name='data',
            name='shipping_address',
            field=models.CharField(default=24227, max_length=200),
            preserve_default=False,
        ),
    ]
