# Generated by Django 4.2.1 on 2023-05-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_rename_address_data_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
