# Generated by Django 4.2.1 on 2023-05-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_alter_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
