# Generated by Django 4.2.3 on 2023-07-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='created_at',
            field=models.DateTimeField(max_length=6),
        ),
    ]
