# Generated by Django 4.2.2 on 2023-06-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_inv', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField()),
            ],
        ),
    ]
