# Generated by Django 4.2.2 on 2023-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_location_remove_bin_name_bin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('shipment', 'shipment'), ('order', 'order'), ('return', 'return'), ('adjustment', 'adjustment')], default='shipment', max_length=10),
        ),
    ]
