# Generated by Django 4.2.2 on 2023-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Inventory', '0003_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='amount_of_bins',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bin',
            name='items',
            field=models.ManyToManyField(blank=True, to='Items.items'),
        ),
    ]
