# Generated by Django 4.2.2 on 2023-06-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_location_amount_of_bins_alter_bin_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='type',
        ),
    ]
