# Generated by Django 4.2.2 on 2023-06-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_orders_ordered_date_orders_updated_date'),
        ('Inventory', '0005_remove_inventory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='inventory',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pick',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
            preserve_default=False,
        ),
    ]
