# Generated by Django 4.2.2 on 2023-06-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_orders_ordered_date_orders_updated_date'),
        ('Inventory', '0006_remove_pick_order_number_remove_pick_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='item',
        ),
        migrations.AddField(
            model_name='pick',
            name='items',
            field=models.ManyToManyField(blank=True, to='Orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.location'),
        ),
    ]
