# Generated by Django 4.2.2 on 2023-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_remove_pick_item_pick_items_alter_pick_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='change',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
