# Generated by Django 4.2.2 on 2023-06-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_inventoryhistory_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='amount_of_bins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
