# Generated by Django 4.2.2 on 2023-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_alter_location_amount_of_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
