# Generated by Django 4.2.2 on 2023-06-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_bin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='type',
            new_name='typeI',
        ),
        migrations.AddField(
            model_name='inventory',
            name='typeI',
            field=models.CharField(choices=[('shipment', 'shipment'), ('order', 'order'), ('return', 'return'), ('adjustment', 'adjustment')], default='shipment', max_length=10),
        ),
    ]
