# Generated by Django 4.2.2 on 2023-06-09 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_inventory_accountsreceivable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='customer',
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customers.orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 7, 9)),
        ),
    ]
