# Generated by Django 4.2.2 on 2023-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='current_inv',
            field=models.IntegerField(default=0),
        ),
    ]
