# Generated by Django 4.2.2 on 2023-06-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Customers', '0009_alter_items_current_inv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='order',
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items'),
        ),
        migrations.DeleteModel(
            name='AccountsReceivable',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
