# Generated by Django 4.2.2 on 2023-06-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_remove_accountsreceivable_order_delete_logmessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
