# Generated by Django 4.2.3 on 2023-08-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('AccountsReceivable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accountsreceivable', to='Orders.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountsreceivablehistory',
            name='accountsreceivable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_accountsreceivablehistory', to='AccountsReceivable.accountsreceivable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountsreceivablepayment',
            name='accountsreceivable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_accountsreceivablepayment', to='AccountsReceivable.accountsreceivable'),
            preserve_default=False,
        ),
    ]
