# Generated by Django 4.2.2 on 2023-06-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsReceivable', '0002_alter_accountsreceivable_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
