# Generated by Django 4.2.2 on 2023-06-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_remove_accountsreceivable_order_delete_logmessage_and_more'),
        ('AccountsReceivable', '0003_alter_accountsreceivable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customers.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
