# Generated by Django 4.2.2 on 2023-06-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsReceivable', '0004_accountsreceivable_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('accounts_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountsReceivable.accountsreceivable')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=100)),
                ('new_value', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accounts_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountsReceivable.accountsreceivable')),
            ],
        ),
    ]
