# Generated by Django 4.2.2 on 2023-06-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsReceivable', '0005_accountsreceivablepayment_accountsreceivablehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='customer',
        ),
    ]
