# Generated by Django 4.2.3 on 2023-08-07 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_orderitem_items_orderitem_orders_orders_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
