# Generated by Django 4.2.2 on 2023-06-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_orders_item_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
